server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zxjy?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useOldAliasMetadataBehavior=true
    username: root
    password: 1234
  mvc:
    view:
      prefix: /templates
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password:
    timeout: 2000

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5

  mail:
    host: smtp.qq.com
    username: 1962765023@qq.com
    password: bxjjughpkcvlecfd
    protocol: smtp
    default-encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true


logging:
  level:
    org.apache.ibatis: debug
    com.zxjx: debug

file:
  head-image-location: F:/workspace-graduate/src/main/resources/static/image/headImage/
  course-image-location: F:/workspace-graduate/src/main/resources/static/image/course/
  resume-image-location: F:/workspace-graduate/src/main/resources/static/image/resume/
  classes-image-location: F:/workspace-graduate/src/main/resources/static/image/classes/
  download-image-location: F:/workspace-graduate/src/main/resources/static/image/download/

# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
